---

- hosts: localhost
  become: true
  vars:
    proxy_server: 127.0.0.1
  roles:
    - role: oracle-java
    - role: nexus
      tags: nexus
    - role: custom-jenkins
      cj_set_proxy: false
      tags: jenkins
